const SERVICES = Object.freeze([
  {
    id: "athena-api",
    name: "Athena API",
    kind: "service",
    owner: "platform",
    criticality: "critical",
    capabilities: ["http", "auth", "workspace"],
    dependsOn: ["main-database", "key-custody", "otel-collector"],
  },
  {
    id: "authentication",
    name: "Authentication",
    kind: "component",
    owner: "security",
    criticality: "critical",
    capabilities: ["password", "passkey", "quick-login", "session"],
    dependsOn: ["athena-api", "main-database", "key-custody"],
  },
  {
    id: "chat-runtime",
    name: "Chat Runtime",
    kind: "component",
    owner: "ai-platform",
    criticality: "critical",
    capabilities: ["sse", "context", "streaming"],
    dependsOn: ["athena-api", "main-database", "model-provider", "rag"],
  },
  {
    id: "agent-runtime",
    name: "Agent Runtime",
    kind: "component",
    owner: "ai-platform",
    criticality: "critical",
    capabilities: ["planning", "tool-routing", "approval", "recovery"],
    dependsOn: ["chat-runtime", "tool-runtime", "model-provider"],
  },
  {
    id: "tool-runtime",
    name: "Tool Runtime",
    kind: "component",
    owner: "ai-platform",
    criticality: "high",
    capabilities: ["builtin-tools", "mcp", "plugins"],
    dependsOn: ["athena-api"],
  },
  {
    id: "crypto-account-access",
    name: "Crypto Account Access",
    kind: "security-sensitive-component",
    owner: "ai-platform",
    criticality: "high",
    capabilities: [
      "gate-read-only",
      "account-scoped-resolution",
      "approval-required-tools",
      "scheduled-preapproval",
    ],
    dependsOn: [
      "authentication",
      "agent-runtime",
      "tool-runtime",
      "key-custody",
      "main-database",
    ],
  },
  {
    id: "rag",
    name: "Knowledge Retrieval",
    kind: "component",
    owner: "knowledge",
    criticality: "high",
    capabilities: ["retrieval", "rerank", "citations"],
    dependsOn: ["vector-database", "embedding-provider"],
  },
  {
    id: "knowledge-ingest",
    name: "Knowledge Ingest",
    kind: "component",
    owner: "knowledge",
    criticality: "high",
    capabilities: ["parse", "chunk", "embed", "index"],
    dependsOn: ["main-database", "vector-database", "embedding-provider"],
  },
  {
    id: "sync-v2",
    name: "Unified Sync V2",
    kind: "control-plane",
    owner: "platform",
    criticality: "critical",
    capabilities: ["state-tree", "outbox", "cursor", "projection"],
    dependsOn: ["main-database", "nats-jetstream"],
  },
  {
    id: "operations-plane",
    name: "AI Operations Plane",
    kind: "control-plane",
    owner: "sre",
    criticality: "high",
    capabilities: ["semantic-events", "timeline", "state-graph"],
    dependsOn: ["nats-jetstream", "clickhouse", "otel-collector"],
  },
  {
    id: "operations-shadow-agents",
    name: "Operations Shadow Agents",
    kind: "diagnostic",
    owner: "sre",
    criticality: "medium",
    capabilities: [
      "advisory-diagnosis",
      "incident-evaluation",
      "evidence-linking",
    ],
    dependsOn: ["operations-plane", "clickhouse", "otel-collector"],
  },
  {
    id: "main-database",
    name: "Primary Database",
    kind: "data-store",
    owner: "platform",
    criticality: "critical",
    capabilities: ["business-authority", "transactions"],
    dependsOn: [],
  },
  {
    id: "vector-database",
    name: "Vector Database",
    kind: "data-store",
    owner: "knowledge",
    criticality: "high",
    capabilities: ["vector-search"],
    dependsOn: [],
  },
  {
    id: "nats-jetstream",
    name: "NATS JetStream",
    kind: "transport",
    owner: "platform",
    criticality: "critical",
    capabilities: ["durable-events", "fanout", "replay"],
    dependsOn: [],
  },
  {
    id: "clickhouse",
    name: "ClickHouse Operations Store",
    kind: "data-store",
    owner: "sre",
    criticality: "high",
    capabilities: ["timeline", "analytics"],
    dependsOn: [],
  },
  {
    id: "otel-collector",
    name: "OpenTelemetry Collector",
    kind: "telemetry",
    owner: "sre",
    criticality: "high",
    capabilities: ["traces", "metrics", "logs"],
    dependsOn: [],
  },
  {
    id: "model-provider",
    name: "Model Provider",
    kind: "external-service",
    owner: "ai-platform",
    criticality: "critical",
    capabilities: ["chat-completion", "streaming"],
    dependsOn: [],
  },
  {
    id: "embedding-provider",
    name: "Embedding Provider",
    kind: "external-service",
    owner: "knowledge",
    criticality: "high",
    capabilities: ["embedding"],
    dependsOn: [],
  },
  {
    id: "key-custody",
    name: "Key Custody",
    kind: "security",
    owner: "security",
    criticality: "critical",
    capabilities: [
      "key-resolution",
      "rotation",
      "quarantine",
      "crypto-suite-registry",
    ],
    dependsOn: [],
  },
  {
    id: "post-quantum-security",
    name: "Post-Quantum Security Controls",
    kind: "security-control",
    owner: "security",
    criticality: "critical",
    capabilities: [
      "runtime-provider-validation",
      "hybrid-signature-validation",
      "hybrid-kem-validation",
      "downgrade-detection",
      "bounded-resilience-testing",
    ],
    dependsOn: ["key-custody", "operations-plane", "otel-collector"],
  },
]);

function serviceCatalog() {
  return SERVICES.map((service) => ({ ...service }));
}

function serviceById(id) {
  const service = SERVICES.find((entry) => entry.id === id);
  return service ? { ...service } : null;
}

module.exports = { serviceById, serviceCatalog };
