import type {
  OpenFuturesPositionItem,
  OpenFuturesPositionsSummary,
} from "./openFuturesPositionsTypes";

export const mockOpenFuturesPositions: OpenFuturesPositionItem[] = [
  {
    id: "btc-usdt-long-10x",
    symbol: "BTCUSDT",
    baseAsset: "BTC",
    quoteAsset: "USD",
    contractType: "perpetual",
    side: "long",
    leverage: 10,
    marginMode: "isolated",
    quantity: "0.2456 BTC",
    notionalUsd: "12104.67",
    positionValueUsd: "12104.67",
    entryPrice: "47820.40",
    markPrice: "49285.30",
    liquidationPrice: "40618.13",
    liquidationDistancePct: "17.58",
    liquidationRiskLevel: "safe",
    marginUsd: "1210.47",
    fundingFeeUsd: "-8.42",
    unrealizedPnlUsd: "359.74",
    pnlPct: "2.97",
    riskLevel: "safe",
    iconUrl: "/crypto-icons/btc.png",
  },
  {
    id: "eth-usdt-short-8x",
    symbol: "ETHUSDT",
    baseAsset: "ETH",
    quoteAsset: "USD",
    contractType: "perpetual",
    side: "short",
    leverage: 8,
    marginMode: "cross",
    quantity: "3.8200 ETH",
    notionalUsd: "9624.10",
    positionValueUsd: "9624.10",
    entryPrice: "2584.18",
    markPrice: "2519.40",
    liquidationPrice: "2840.36",
    liquidationDistancePct: "12.74",
    liquidationRiskLevel: "watch",
    marginUsd: "1203.01",
    fundingFeeUsd: "4.18",
    unrealizedPnlUsd: "247.46",
    pnlPct: "2.57",
    riskLevel: "safe",
    iconUrl: "/crypto-icons/eth.png",
  },
  {
    id: "sol-usdt-long-5x",
    symbol: "SOLUSDT",
    baseAsset: "SOL",
    quoteAsset: "USD",
    contractType: "perpetual",
    side: "long",
    leverage: 5,
    marginMode: "cross",
    quantity: "26.4000 SOL",
    notionalUsd: "3759.24",
    positionValueUsd: "3759.24",
    entryPrice: "139.62",
    markPrice: "142.40",
    liquidationPrice: "131.72",
    liquidationDistancePct: "7.50",
    liquidationRiskLevel: "danger",
    marginUsd: "751.85",
    fundingFeeUsd: "-2.13",
    unrealizedPnlUsd: "73.39",
    pnlPct: "1.95",
    riskLevel: "watch",
    iconUrl: "/crypto-icons/sol.png",
  },
  {
    id: "bnb-usdt-long-3x",
    symbol: "BNBUSDT",
    baseAsset: "BNB",
    quoteAsset: "USD",
    contractType: "perpetual",
    side: "long",
    leverage: 3,
    marginMode: "cross",
    quantity: "4.1800 BNB",
    notionalUsd: "2684.31",
    positionValueUsd: "2684.31",
    entryPrice: "634.22",
    markPrice: "642.18",
    liquidationPrice: "626.77",
    liquidationDistancePct: "2.40",
    liquidationRiskLevel: "critical",
    marginUsd: "894.77",
    fundingFeeUsd: null,
    unrealizedPnlUsd: "33.27",
    pnlPct: "1.24",
    riskLevel: "danger",
    iconUrl: "/crypto-icons/bnb.png",
  },
  {
    id: "xrp-usdt-short-6x",
    symbol: "XRPUSDT",
    baseAsset: "XRP",
    quoteAsset: "USD",
    contractType: "perpetual",
    side: "short",
    leverage: 6,
    marginMode: "isolated",
    quantity: "3451.0000 XRP",
    notionalUsd: "2139.58",
    positionValueUsd: "2139.58",
    entryPrice: "0.6420",
    markPrice: "0.6200",
    liquidationPrice: "0.6249",
    liquidationDistancePct: "0.80",
    liquidationRiskLevel: "extreme",
    marginUsd: "356.60",
    fundingFeeUsd: "1.06",
    unrealizedPnlUsd: "75.92",
    pnlPct: "3.55",
    riskLevel: "danger",
    iconUrl: "/crypto-icons/xrp.png",
  },
  {
    id: "doge-usdt-short-3x",
    symbol: "DOGEUSDT",
    baseAsset: "DOGE",
    quoteAsset: "USD",
    contractType: "perpetual",
    side: "short",
    leverage: 3,
    marginMode: "cross",
    quantity: "9600.0000 DOGE",
    notionalUsd: "1614.61",
    positionValueUsd: "1614.61",
    entryPrice: "0.1742",
    markPrice: "0.1682",
    liquidationPrice: "0.2246",
    liquidationDistancePct: "33.53",
    liquidationRiskLevel: "safe",
    marginUsd: "538.20",
    fundingFeeUsd: "-0.84",
    unrealizedPnlUsd: "57.60",
    pnlPct: "3.57",
    riskLevel: "danger",
    iconUrl: "/crypto-icons/doge.png",
  },
];

export const mockOpenFuturesSummary: OpenFuturesPositionsSummary = {
  totalUnrealizedPnlUsd: "847.38",
  weightedPnlPct: "2.58",
  totalMarginUsd: "4954.90",
  accountEquityUsd: "48747.95",
  marginRatioPct: "10.16",
};
