import type { TradeRecordItem, TradeRecordsSummary } from "./tradeRecordsTypes";

const now = Date.now();
const hour = 60 * 60 * 1000;

function mockRecord(record: TradeRecordItem): TradeRecordItem {
  return record;
}

export const mockTradeRecords: TradeRecordItem[] = [
  mockRecord({
    id: "spot-btc-buy-001",
    ts: now - hour,
    marketType: "spot",
    symbol: "BTCUSDT",
    baseAsset: "BTC",
    quoteAsset: "USDT",
    contractType: "spot",
    action: "spot_buy",
    quantity: "0.0845",
    price: "104582.32",
    notionalUsd: "8838.20",
    feeUsd: "8.8400",
    feeAmount: "0.00008453",
    feeCurrency: "BTC",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "0.00008453",
    feeDisplayCurrency: "BTC",
    realizedPnlUsd: null,
    orderId: "gt-spot-btc-78412001",
    iconUrl: "/crypto-icons/btc.png",
  }),
  mockRecord({
    id: "futures-btc-open-long-002",
    ts: now - hour * 1.5,
    marketType: "futures",
    symbol: "BTCUSDT",
    baseAsset: "BTC",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_open_long",
    quantity: "0.1200",
    price: "105420.10",
    notionalUsd: "12650.41",
    feeUsd: "5.0600",
    feeAmount: "5.06",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "5.06",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "0.00",
    orderId: "gt-fut-btc-new-open",
    iconUrl: "/crypto-icons/btc.png",
    cycleId: "cycle:BTCUSDT:perpetual:long:mock:002",
    cycleStatus: "open",
    cycleConfidence: "partial_history",
    matchRole: "open",
    matchedQty: "0.12",
    matchWarning: "partial_history",
  }),
  mockRecord({
    id: "futures-btc-close-long-002",
    ts: now - hour * 2,
    marketType: "futures",
    symbol: "BTCUSDT",
    baseAsset: "BTC",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_close_long",
    quantity: "0.1000",
    price: "105180.20",
    notionalUsd: "10518.02",
    feeUsd: "4.2100",
    feeAmount: "4.21",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "4.21",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "125.97",
    orderId: "gt-fut-btc-close-final",
    iconUrl: "/crypto-icons/btc.png",
    cycleId: "cycle:BTCUSDT:perpetual:long:mock:001",
    cycleStatus: "closed",
    cycleConfidence: "complete",
    matchRole: "close",
    matchedQty: "0.1",
  }),
  mockRecord({
    id: "futures-eth-close-short-001",
    ts: now - hour * 3,
    marketType: "futures",
    symbol: "ETHUSDT",
    baseAsset: "ETH",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_close_short",
    quantity: "5.4000",
    price: "2578.34",
    notionalUsd: "13923.04",
    feeUsd: "5.5700",
    feeAmount: "5.57",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "5.57",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "234.68",
    orderId: "gt-fut-eth-close-short",
    iconUrl: "/crypto-icons/eth.png",
    cycleId: "cycle:ETHUSDT:perpetual:short:mock:001",
    cycleStatus: "closed",
    cycleConfidence: "complete",
    matchRole: "close",
    matchedQty: "5.4",
  }),
  mockRecord({
    id: "futures-xrp-close-short-boundary",
    ts: now - hour * 4,
    marketType: "futures",
    symbol: "XRPUSDT",
    baseAsset: "XRP",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_close_short",
    quantity: "6200.0000",
    price: "0.6524",
    notionalUsd: "4044.88",
    feeUsd: "1.6200",
    feeAmount: "1.62",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "1.62",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "-89.28",
    orderId: "gt-fut-xrp-first-close",
    iconUrl: "/crypto-icons/xrp.png",
    cycleId: "cycle:XRPUSDT:perpetual:short:boundary:001",
    cycleStatus: "unmatched",
    cycleConfidence: "unmatched",
    matchRole: "unmatched_close",
    matchedQty: "0",
    matchWarning: "missing_open_before_window",
  }),
  mockRecord({
    id: "futures-ada-close-long-over",
    ts: now - hour * 5,
    marketType: "futures",
    symbol: "ADAUSDT",
    baseAsset: "ADA",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_close_long",
    quantity: "1500.0000",
    price: "0.7210",
    notionalUsd: "1081.50",
    feeUsd: "0.4300",
    feeAmount: "0.43",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "0.43",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "91.00",
    orderId: "gt-fut-ada-close-over",
    iconUrl: "/crypto-icons/ada.png",
    cycleId: "cycle:ADAUSDT:perpetual:long:mock:001",
    cycleStatus: "partial",
    cycleConfidence: "partial_history",
    matchRole: "unmatched_close",
    matchedQty: "1000",
    matchWarning: "unmatched_close",
  }),
  mockRecord({
    id: "futures-btc-close-long-001",
    ts: now - hour * 6,
    marketType: "futures",
    symbol: "BTCUSDT",
    baseAsset: "BTC",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_close_long",
    quantity: "0.0800",
    price: "104780.40",
    notionalUsd: "8382.43",
    feeUsd: "3.3500",
    feeAmount: "3.35",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "3.35",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "72.30",
    orderId: "gt-fut-btc-close-partial",
    iconUrl: "/crypto-icons/btc.png",
    cycleId: "cycle:BTCUSDT:perpetual:long:mock:001",
    cycleStatus: "closed",
    cycleConfidence: "complete",
    matchRole: "close",
    matchedQty: "0.08",
  }),
  mockRecord({
    id: "futures-sol-close-long-memory",
    ts: now - hour * 7,
    marketType: "futures",
    symbol: "SOLUSDT",
    baseAsset: "SOL",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_close_long",
    quantity: "18.0000",
    price: "164.80",
    notionalUsd: "2966.40",
    feeUsd: "1.1900",
    feeAmount: "1.19",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "1.19",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "118.20",
    orderId: "gt-fut-sol-close-memory",
    iconUrl: "/crypto-icons/sol.png",
    cycleId: "cycle:SOLUSDT:perpetual:long:memory:001",
    cycleStatus: "closed",
    cycleConfidence: "complete",
    matchRole: "close",
    matchedQty: "18",
    matchWarning: "window_boundary",
  }),
  mockRecord({
    id: "futures-eth-open-short-001",
    ts: now - hour * 10,
    marketType: "futures",
    symbol: "ETHUSDT",
    baseAsset: "ETH",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_open_short",
    quantity: "5.4000",
    price: "2621.80",
    notionalUsd: "14157.72",
    feeUsd: "5.6600",
    feeAmount: "5.66",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "5.66",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "0.00",
    orderId: "gt-fut-eth-open-short",
    iconUrl: "/crypto-icons/eth.png",
    cycleId: "cycle:ETHUSDT:perpetual:short:mock:001",
    cycleStatus: "closed",
    cycleConfidence: "complete",
    matchRole: "open",
    matchedQty: "5.4",
  }),
  mockRecord({
    id: "futures-ada-open-long-001",
    ts: now - hour * 12,
    marketType: "futures",
    symbol: "ADAUSDT",
    baseAsset: "ADA",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_open_long",
    quantity: "1000.0000",
    price: "0.6300",
    notionalUsd: "630.00",
    feeUsd: "0.2500",
    feeAmount: "0.25",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "0.25",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "0.00",
    orderId: "gt-fut-ada-open",
    iconUrl: "/crypto-icons/ada.png",
    cycleId: "cycle:ADAUSDT:perpetual:long:mock:001",
    cycleStatus: "partial",
    cycleConfidence: "partial_history",
    matchRole: "open",
    matchedQty: "1000",
  }),
  mockRecord({
    id: "futures-btc-open-long-add",
    ts: now - hour * 14,
    marketType: "futures",
    symbol: "BTCUSDT",
    baseAsset: "BTC",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_open_long",
    quantity: "0.0800",
    price: "103920.50",
    notionalUsd: "8313.64",
    feeUsd: "3.3300",
    feeAmount: "3.33",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "3.33",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "0.00",
    orderId: "gt-fut-btc-open-add",
    iconUrl: "/crypto-icons/btc.png",
    cycleId: "cycle:BTCUSDT:perpetual:long:mock:001",
    cycleStatus: "closed",
    cycleConfidence: "complete",
    matchRole: "open",
    matchedQty: "0.08",
  }),
  mockRecord({
    id: "futures-btc-open-long-001",
    ts: now - hour * 16,
    marketType: "futures",
    symbol: "BTCUSDT",
    baseAsset: "BTC",
    quoteAsset: "USDT",
    contractType: "perpetual",
    action: "futures_open_long",
    quantity: "0.1000",
    price: "103250.70",
    notionalUsd: "10325.07",
    feeUsd: "4.1300",
    feeAmount: "4.13",
    feeCurrency: "USDT",
    feeSource: "asset",
    pointFeeAmount: "0",
    gtFeeAmount: "0",
    feeDisplayAmount: "4.13",
    feeDisplayCurrency: "USDT",
    realizedPnlUsd: "0.00",
    orderId: "gt-fut-btc-open-first",
    iconUrl: "/crypto-icons/btc.png",
    cycleId: "cycle:BTCUSDT:perpetual:long:mock:001",
    cycleStatus: "closed",
    cycleConfidence: "complete",
    matchRole: "open",
    matchedQty: "0.1",
  }),
  mockRecord({
    id: "spot-eth-buy-001",
    ts: now - hour * 18,
    marketType: "spot",
    symbol: "ETHUSDT",
    baseAsset: "ETH",
    quoteAsset: "USDT",
    contractType: "spot",
    action: "spot_buy",
    quantity: "3.2500",
    price: "2588.42",
    notionalUsd: "8412.37",
    feeUsd: "0.0000",
    feeAmount: "0",
    feeCurrency: "ETH",
    feeSource: "point",
    pointFeeAmount: "8.41",
    gtFeeAmount: "0",
    feeDisplayAmount: "8.41",
    feeDisplayCurrency: "点卡抵扣",
    realizedPnlUsd: null,
    orderId: "gt-spot-eth-78412003",
    iconUrl: "/crypto-icons/eth.png",
  }),
];

function parseNumber(value?: string | null) {
  const number = Number(String(value || "0").replace(/,/g, ""));
  return Number.isFinite(number) ? number : 0;
}

export function summarizeTradeRecords(
  records: TradeRecordItem[]
): TradeRecordsSummary {
  const realized = records.filter((record) => record.realizedPnlUsd !== null);
  const wins = realized.filter(
    (record) => parseNumber(record.realizedPnlUsd) > 0
  );
  const totalNotionalUsd = records.reduce(
    (sum, record) => sum + parseNumber(record.notionalUsd),
    0
  );
  const totalFeeUsd = records.reduce(
    (sum, record) => sum + parseNumber(record.feeUsd),
    0
  );
  const totalRealizedPnlUsd = realized.reduce(
    (sum, record) => sum + parseNumber(record.realizedPnlUsd),
    0
  );
  const spotNotionalUsd = records
    .filter((record) => record.marketType === "spot")
    .reduce((sum, record) => sum + parseNumber(record.notionalUsd), 0);
  const futuresNotionalUsd = records
    .filter((record) => record.marketType === "futures")
    .reduce((sum, record) => sum + parseNumber(record.notionalUsd), 0);

  return {
    totalNotionalUsd: totalNotionalUsd.toFixed(2),
    totalFeeUsd: totalFeeUsd.toFixed(2),
    totalRealizedPnlUsd: totalRealizedPnlUsd.toFixed(2),
    winRatePct: realized.length
      ? ((wins.length / realized.length) * 100).toFixed(2)
      : "0.00",
    tradeCount: records.length,
    spotNotionalUsd: spotNotionalUsd.toFixed(2),
    futuresNotionalUsd: futuresNotionalUsd.toFixed(2),
  };
}

export const mockTradeRecordsSummary = summarizeTradeRecords(mockTradeRecords);
