import type { TradingPairPreset } from "./tradingPairDetailTypes";

export const tradingPairMockPresets: TradingPairPreset[] = [
  {
    id: "BTC_USDT",
    baseAsset: "BTC",
    quoteAsset: "USDT",
    symbol: "BTC/USDT",
    gateCurrencyPair: "BTC_USDT",
    assetName: "Bitcoin",
    assetNameCn: "比特币",
    iconText: "₿",
    iconImage: "/crypto-icons/btc.png",
    accentColor: "#F4B23E",
    holdingValueQuote: "128567.32",
    holdingValueUsd: "128567.32",
    change24hPct: "1.82",
    change24hQuote: "2296.41",
    averageBuyPriceQuote: "62842.15",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "104567.89",
    holdingAmountBase: "1.228743",
  },
  {
    id: "ETH_USDT",
    baseAsset: "ETH",
    quoteAsset: "USDT",
    symbol: "ETH/USDT",
    gateCurrencyPair: "ETH_USDT",
    assetName: "Ethereum",
    assetNameCn: "以太坊",
    iconText: "Ξ",
    iconImage: "/crypto-icons/eth.png",
    accentColor: "#8EA2FF",
    holdingValueQuote: "9283.95",
    holdingValueUsd: "9283.95",
    change24hPct: "-0.64",
    change24hQuote: "-59.42",
    averageBuyPriceQuote: "2820.44",
    averageBuyPriceMethod: "recent_weighted",
    currentPriceQuote: "1573.29",
    holdingAmountBase: "5.900984",
  },
  {
    id: "SOL_USDT",
    baseAsset: "SOL",
    quoteAsset: "USDT",
    symbol: "SOL/USDT",
    gateCurrencyPair: "SOL_USDT",
    assetName: "Solana",
    assetNameCn: "索拉纳",
    iconText: "SOL",
    iconImage: "/crypto-icons/sol.png",
    accentColor: "#cb3dff",
    holdingValueQuote: "18942.11",
    holdingValueUsd: "18942.11",
    change24hPct: "3.28",
    change24hQuote: "601.48",
    averageBuyPriceQuote: "138.72",
    averageBuyPriceMethod: "manual",
    currentPriceQuote: "162.45",
    holdingAmountBase: "116.6027",
  },
  {
    id: "XRP_USDT",
    baseAsset: "XRP",
    quoteAsset: "USDT",
    symbol: "XRP/USDT",
    gateCurrencyPair: "XRP_USDT",
    assetName: "XRP",
    assetNameCn: "瑞波币",
    iconText: "X",
    iconImage: "/crypto-icons/xrp.png",
    accentColor: "#F8FAFC",
    holdingValueQuote: "12680.44",
    holdingValueUsd: "12680.44",
    change24hPct: "-1.13",
    change24hQuote: "-145.02",
    averageBuyPriceQuote: "0.52",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "0.61",
    holdingAmountBase: "20787.6065",
  },
  {
    id: "DOGE_USDT",
    baseAsset: "DOGE",
    quoteAsset: "USDT",
    symbol: "DOGE/USDT",
    gateCurrencyPair: "DOGE_USDT",
    assetName: "Dogecoin",
    assetNameCn: "狗狗币",
    iconText: "Ð",
    iconImage: "/crypto-icons/doge.png",
    accentColor: "#D6A84F",
    holdingValueQuote: "8460.20",
    holdingValueUsd: "8460.20",
    change24hPct: "2.41",
    change24hQuote: "198.92",
    averageBuyPriceQuote: "0.13",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "0.18",
    holdingAmountBase: "47001.112",
  },
  {
    id: "SUI_USDT",
    baseAsset: "SUI",
    quoteAsset: "USDT",
    symbol: "SUI/USDT",
    gateCurrencyPair: "SUI_USDT",
    assetName: "Sui",
    assetNameCn: "Sui",
    iconText: "SUI",
    iconImage: "/crypto-icons/sui.png",
    accentColor: "#38BDF8",
    holdingValueQuote: "10324.72",
    holdingValueUsd: "10324.72",
    change24hPct: "1.06",
    change24hQuote: "108.27",
    averageBuyPriceQuote: "2.86",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "3.12",
    holdingAmountBase: "3309.2051",
  },
  {
    id: "BNB_USDT",
    baseAsset: "BNB",
    quoteAsset: "USDT",
    symbol: "BNB/USDT",
    gateCurrencyPair: "BNB_USDT",
    assetName: "BNB",
    assetNameCn: "币安币",
    iconText: "BNB",
    iconImage: "/crypto-icons/bnb.png",
    accentColor: "#F3BA2F",
    holdingValueQuote: "15210.33",
    holdingValueUsd: "15210.33",
    change24hPct: "-0.38",
    change24hQuote: "-58.12",
    averageBuyPriceQuote: "604.18",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "641.85",
    holdingAmountBase: "23.6974",
  },
  {
    id: "ADA_USDT",
    baseAsset: "ADA",
    quoteAsset: "USDT",
    symbol: "ADA/USDT",
    gateCurrencyPair: "ADA_USDT",
    assetName: "Cardano",
    assetNameCn: "艾达币",
    iconText: "ADA",
    iconImage: "/crypto-icons/ada.png",
    accentColor: "#A3A3A3",
    holdingValueQuote: "6920.44",
    holdingValueUsd: "6920.44",
    change24hPct: "0.88",
    change24hQuote: "60.34",
    averageBuyPriceQuote: "0.56",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "0.63",
    holdingAmountBase: "10984.825",
  },
  {
    id: "NEAR_USDT",
    baseAsset: "NEAR",
    quoteAsset: "USDT",
    symbol: "NEAR/USDT",
    gateCurrencyPair: "NEAR_USDT",
    assetName: "NEAR Protocol",
    assetNameCn: "NEAR",
    iconText: "N",
    iconImage: "/crypto-icons/near.png",
    accentColor: "#F8FAFC",
    holdingValueQuote: "7345.18",
    holdingValueUsd: "7345.18",
    change24hPct: "-0.71",
    change24hQuote: "-52.21",
    averageBuyPriceQuote: "2.34",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "2.78",
    holdingAmountBase: "2642.151",
  },
  {
    id: "ONDO_USDT",
    baseAsset: "ONDO",
    quoteAsset: "USDT",
    symbol: "ONDO/USDT",
    gateCurrencyPair: "ONDO_USDT",
    assetName: "Ondo",
    assetNameCn: "Ondo",
    iconText: "O",
    iconImage: "/crypto-icons/ondo.png",
    accentColor: "#F8FAFC",
    holdingValueQuote: "5818.73",
    holdingValueUsd: "5818.73",
    change24hPct: "1.37",
    change24hQuote: "78.66",
    averageBuyPriceQuote: "0.74",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "0.89",
    holdingAmountBase: "6537.899",
  },
  {
    id: "GT_USDT",
    baseAsset: "GT",
    quoteAsset: "USDT",
    symbol: "GT/USDT",
    gateCurrencyPair: "GT_USDT",
    assetName: "GateToken",
    assetNameCn: "GateToken",
    iconText: "GT",
    iconImage: "/crypto-icons/gt.png",
    accentColor: "#1D4ED8",
    holdingValueQuote: "9820.15",
    holdingValueUsd: "9820.15",
    change24hPct: "0.52",
    change24hQuote: "50.84",
    averageBuyPriceQuote: "16.42",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "18.27",
    holdingAmountBase: "537.499",
  },
  {
    id: "LTC_USDT",
    baseAsset: "LTC",
    quoteAsset: "USDT",
    symbol: "LTC/USDT",
    gateCurrencyPair: "LTC_USDT",
    assetName: "Litecoin",
    assetNameCn: "莱特币",
    iconText: "Ł",
    iconImage: "/crypto-icons/ltc.png",
    accentColor: "#CBD5E1",
    holdingValueQuote: "7240.83",
    holdingValueUsd: "7240.83",
    change24hPct: "0.42",
    change24hQuote: "30.12",
    averageBuyPriceQuote: null,
    averageBuyPriceMethod: "unknown",
    currentPriceQuote: "86.18",
    holdingAmountBase: "84.0193",
  },
  {
    id: "TRX_USDT",
    baseAsset: "TRX",
    quoteAsset: "USDT",
    symbol: "TRX/USDT",
    gateCurrencyPair: "TRX_USDT",
    assetName: "TRON",
    assetNameCn: "波场",
    iconText: "TRX",
    iconImage: "/crypto-icons/trx.png",
    accentColor: "#EF4444",
    holdingValueQuote: "6420.35",
    holdingValueUsd: "6420.35",
    change24hPct: "0.76",
    change24hQuote: "48.35",
    averageBuyPriceQuote: "0.12",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "0.29",
    holdingAmountBase: "22139.138",
  },
  {
    id: "LINK_USDT",
    baseAsset: "LINK",
    quoteAsset: "USDT",
    symbol: "LINK/USDT",
    gateCurrencyPair: "LINK_USDT",
    assetName: "Chainlink",
    assetNameCn: "Chainlink",
    iconText: "LINK",
    iconImage: "/crypto-icons/link.png",
    accentColor: "#2A5ADA",
    holdingValueQuote: "5348.60",
    holdingValueUsd: "5348.60",
    change24hPct: "1.94",
    change24hQuote: "101.83",
    averageBuyPriceQuote: "13.42",
    averageBuyPriceMethod: "recent_weighted",
    currentPriceQuote: "16.72",
    holdingAmountBase: "319.892",
  },
  {
    id: "OKB_USDT",
    baseAsset: "OKB",
    quoteAsset: "USDT",
    symbol: "OKB/USDT",
    gateCurrencyPair: "OKB_USDT",
    assetName: "OKB",
    assetNameCn: "OKB",
    iconText: "OKB",
    iconImage: "/crypto-icons/okb.png",
    accentColor: "#2563EB",
    holdingValueQuote: "11824.91",
    holdingValueUsd: "11824.91",
    change24hPct: "-0.44",
    change24hQuote: "-52.31",
    averageBuyPriceQuote: "41.20",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "53.36",
    holdingAmountBase: "221.605",
  },
  {
    id: "GUSD_USDT",
    baseAsset: "GUSD",
    quoteAsset: "USDT",
    symbol: "GUSD/USDT",
    gateCurrencyPair: "GUSD_USDT",
    assetName: "Gemini Dollar",
    assetNameCn: "Gemini Dollar",
    iconText: "GUSD",
    iconImage: "/crypto-icons/gusd.png",
    accentColor: "#22D3EE",
    holdingValueQuote: "4380.00",
    holdingValueUsd: "4380.00",
    change24hPct: "0.01",
    change24hQuote: "0.44",
    averageBuyPriceQuote: "1.00",
    averageBuyPriceMethod: "manual",
    currentPriceQuote: "1.00",
    holdingAmountBase: "4380.00",
  },
  {
    id: "USDC_USDT",
    baseAsset: "USDC",
    quoteAsset: "USDT",
    symbol: "USDC/USDT",
    gateCurrencyPair: "USDC_USDT",
    assetName: "USD Coin",
    assetNameCn: "USD Coin",
    iconText: "USDC",
    iconImage: "/crypto-icons/usdc.png",
    accentColor: "#2775CA",
    holdingValueQuote: "18420.00",
    holdingValueUsd: "18420.00",
    change24hPct: "-0.02",
    change24hQuote: "-3.68",
    averageBuyPriceQuote: "1.00",
    averageBuyPriceMethod: "manual",
    currentPriceQuote: "1.00",
    holdingAmountBase: "18420.00",
  },
  {
    id: "USDT_USD",
    baseAsset: "USDT",
    quoteAsset: "USD",
    symbol: "USDT/USD",
    gateCurrencyPair: "USDT_USD",
    assetName: "Tether USDt",
    assetNameCn: "泰达币",
    iconText: "USDT",
    iconImage: "/crypto-icons/usdt.png",
    accentColor: "#26A17B",
    holdingValueQuote: "52800.00",
    holdingValueUsd: "52800.00",
    change24hPct: "0.00",
    change24hQuote: "0.00",
    averageBuyPriceQuote: "1.00",
    averageBuyPriceMethod: "manual",
    currentPriceQuote: "1.00",
    holdingAmountBase: "52800.00",
  },
  {
    id: "XAUT_USDT",
    baseAsset: "XAUT",
    quoteAsset: "USDT",
    symbol: "XAUT/USDT",
    gateCurrencyPair: "XAUT_USDT",
    assetName: "Tether Gold",
    assetNameCn: "Tether Gold",
    iconText: "XAUT",
    iconImage: "/crypto-icons/xaut.png",
    accentColor: "#D6A84F",
    holdingValueQuote: "9480.55",
    holdingValueUsd: "9480.55",
    change24hPct: "0.31",
    change24hQuote: "29.27",
    averageBuyPriceQuote: "2350.00",
    averageBuyPriceMethod: "moving_weighted",
    currentPriceQuote: "2370.14",
    holdingAmountBase: "4.0000",
  },
  {
    id: "HYPE_USDT",
    baseAsset: "HYPE",
    quoteAsset: "USDT",
    symbol: "HYPE/USDT",
    gateCurrencyPair: "HYPE_USDT",
    assetName: "Hyperliquid",
    assetNameCn: "Hyperliquid",
    iconText: "HYPE",
    iconImage: "/crypto-icons/hype.png",
    accentColor: "#2DD4BF",
    holdingValueQuote: "4218.90",
    holdingValueUsd: "4218.90",
    change24hPct: "4.12",
    change24hQuote: "166.96",
    averageBuyPriceQuote: "24.80",
    averageBuyPriceMethod: "recent_weighted",
    currentPriceQuote: "31.25",
    holdingAmountBase: "135.0048",
  },
  {
    id: "PEPE_USDT",
    baseAsset: "PEPE",
    quoteAsset: "USDT",
    symbol: "PEPE/USDT",
    gateCurrencyPair: "PEPE_USDT",
    assetName: "Pepe",
    assetNameCn: "Pepe",
    iconText: "PEPE",
    iconImage: "/crypto-icons/pepe.png",
    accentColor: "#22C55E",
    holdingValueQuote: "2660.44",
    holdingValueUsd: "2660.44",
    change24hPct: "-2.08",
    change24hQuote: "-56.52",
    averageBuyPriceQuote: "0.000009",
    averageBuyPriceMethod: "manual",
    currentPriceQuote: "0.000011",
    holdingAmountBase: "241858181.82",
  },
];

export function presetById(id: string) {
  return (
    tradingPairMockPresets.find((preset) => preset.id === id) ||
    tradingPairMockPresets[0]
  );
}
