const SECRET_VERSION = "v1";
const SECRET_PREFIX = `enc:${SECRET_VERSION}:`;
const ENCRYPTION_ALGORITHM = "aes-256-gcm";
const MASTER_KEY_ENV = "ENCRYPTION_MASTER_KEY";

module.exports = {
  SECRET_PREFIX,
  SECRET_VERSION,
  ENCRYPTION_ALGORITHM,
  MASTER_KEY_ENV,
};
