const SECRET_VERSION = "v2";
const SECRET_PREFIX = `enc:${SECRET_VERSION}:`;
const LEGACY_SECRET_PREFIX = "enc:v1:";
const ENCRYPTION_ALGORITHM = "aes-256-gcm";
const MASTER_KEY_ENV = "ENCRYPTION_MASTER_KEY";

module.exports = {
  SECRET_PREFIX,
  SECRET_VERSION,
  LEGACY_SECRET_PREFIX,
  ENCRYPTION_ALGORITHM,
  MASTER_KEY_ENV,
};
