const GRAPH_VERSION = "knowledge-graph-v1";
const EXTRACTION_PROMPT_VERSION = "kg-extraction-v1";
const MERGE_LOGIC_VERSION = "kg-merge-v1";
const RELATION_ONTOLOGY_VERSION = "relation-ontology-v1";
const NODE_EMBEDDING_VERSION = "kg-node-embedding-v1";
const LABEL_TRANSLATION_PROMPT_VERSION = "kg-label-translation-v1";

const DEFAULT_EXTRACTION_MODEL =
  process.env.KNOWLEDGE_GRAPH_DEEPSEEK_MODEL || "deepseek-v4-flash";
const ENABLE_NODE_EMBEDDINGS =
  process.env.KNOWLEDGE_GRAPH_ENABLE_NODE_EMBEDDINGS === "true";

module.exports = {
  GRAPH_VERSION,
  EXTRACTION_PROMPT_VERSION,
  MERGE_LOGIC_VERSION,
  RELATION_ONTOLOGY_VERSION,
  NODE_EMBEDDING_VERSION,
  LABEL_TRANSLATION_PROMPT_VERSION,
  DEFAULT_EXTRACTION_MODEL,
  ENABLE_NODE_EMBEDDINGS,
};
