server:
  http_listen_port: 3200

query_frontend:
  max_outstanding_per_tenant: 100
  search:
    concurrent_jobs: 16
    target_bytes_per_job: 16777216

querier:
  max_concurrent_queries: 2

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/blocks
    wal:
      path: /var/tempo/wal
